# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "Rakefile","readme.md" ,"changelog.md"]

auto: true
safe: false
pygments: true
baseurl: /

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : R42
tagline: Fun comes first
author :
  name : 
  email : 
  github : https://github.com/R42
  twitter : https://twitter.com/_r42

